name: Build Eleventy and Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build Eleventy project
        run: npm run build    

      # - name: Push to GitHub Pages branch `gh-pages`
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     publish_dir: ./_site
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Deploy to Github Pages
        uses: actions/upload-pages-artifact
        with: 
          path: _site/